/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Ctrl_Categoria;
import Modelo.Categoria;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMIRA
 */
public class FrmCategoria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCategoria.class.getName());

    /**
     * Creates new form FrmCategoria
     */
    public FrmCategoria() {
        initComponents();
        // Solo cierra el formulario actual
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        // Llama a la funcion para cargar los datos de la DB
        cargarTabla();
        // Desabilitar el panel
        habilitarPanel(false);
    }

    // Crear variable global para esta pantalla
    int codigo = 0;

    private void cargarTabla() {
        try {

            Ctrl_Categoria control = new Ctrl_Categoria();

            DefaultTableModel modelo
                    = (DefaultTableModel) tbLista.getModel();

            modelo.setRowCount(0); // Limpiar todos los registro de la tabla

            // Llenar los datos en la tabla
            for (Categoria cat : control.listar(txtBuscar.getText())) {
                modelo.addRow(new Object[]{
                    cat.getIdCategoria(),
                    cat.getDescripcion(),
                    cat.getEstado()
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void habilitarPanel(Boolean condicion) {
        for (Component c : panelPrincipal.getComponents()) {
            c.setEnabled(condicion);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        panelPrincipal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        txtDescripcion = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btAnular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar");

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "DESCRIPCION", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tbLista);

        jLabel7.setText("Estado");

        jLabel2.setText("Descripcion");

        chkEstado.addActionListener(this::chkEstadoActionPerformed);

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(this::btGuardarActionPerformed);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(this::btCancelarActionPerformed);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEstado)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btGuardar)
                .addGap(29, 29, 29)
                .addComponent(btCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(chkEstado))
                .addGap(30, 30, 30)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btNuevo.setText("NUEVO");
        btNuevo.addActionListener(this::btNuevoActionPerformed);

        btEditar.setText("EDITAR");
        btEditar.addActionListener(this::btEditarActionPerformed);

        btAnular.setText("ANULAR");
        btAnular.addActionListener(this::btAnularActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditar)
                        .addGap(26, 26, 26)
                        .addComponent(btAnular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btNuevo)
                            .addComponent(btEditar)
                            .addComponent(btAnular)))
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void chkEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstadoActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        // 1. Verificar que las cajas de texto tengan datos
        if (txtDescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los datos son obligatorios");
            return;
        }

        // 2. Crear el objeto cliente y asignar valores a sus metodos desde las cajas de texto
        Categoria client = new Categoria();
        client.setDescripcion(txtDescripcion.getText().trim());

        if (chkEstado.isSelected()) {
            client.setEstado(1);
        } else {
            client.setEstado(0);
        }
        client.setIdCategoria(codigo);

        // 3. Cear un objeto del controlador cliente
        try {
            Ctrl_Categoria control = new Ctrl_Categoria();

            // Si codigo es CERO, entonces insertar nuevo registro, caso contrario actualizar
            if (codigo == 0) {
                // Verifica duplicado
                var rpta = control.existeCategoria(client.getDescripcion());
                if (rpta) {
                    JOptionPane.showMessageDialog(this, "Descripcion duplicado, ya existe en la BD");
                    return;
                }

                // 4. Usar la funcion guardar del objeto controlador cliente
                var respuesta = control.guardar(client);
                // 5. Si todo es correcto, limpiar las cajas de texto, volver a llamar la funcion listar y mostrar un mensaje de datos grabados correctamente
                if (respuesta) {
                    txtDescripcion.setText("");
                    JOptionPane.showMessageDialog(this, "Grabado correctamente");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el cliente");
                }
            } else {
                // Actualizar
                // Pasar el id del cliente
                //client.setIdCliente(codigo);
                var respuesta = control.actualizar(client);
                // 5. Si todo es correcto, limpiar las cajas de texto, volver a llamar la funcion listar y mostrar un mensaje de datos grabados correctamente
                if (respuesta) {
                    txtDescripcion.setText("");
                    
                    JOptionPane.showMessageDialog(this, "Grabado correctamente");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el cliente");
                }
            }

            // Muestra nuevamente los datos desde la BD
            cargarTabla();

            // Dejamos a la variable codigo con su valor incial = 0
            codigo = 0;

            // Deshabilitar el panel
            habilitarPanel(false);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        codigo = 0;
        txtDescripcion.setText("");
        habilitarPanel(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        // TODO add your handling code here:
        // Habilitar los controles del panel
        habilitarPanel(true);
        codigo = 0;
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        // Leer la fila seleccionada
        int fila = tbLista.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una descripcion");
            return;
        }

        // Pasamos los datos de la fila seleccionada a los TextField
        codigo = Integer.parseInt(tbLista.getValueAt(fila, 0).toString());
        txtDescripcion.setText(tbLista.getValueAt(fila, 1).toString());
        if ((Integer) tbLista.getValueAt(fila, 2) == 0) {
            chkEstado.setSelected(false);
        } else {
            chkEstado.setSelected(true);
        }

        // Habilitar el panel
        habilitarPanel(true);
    }//GEN-LAST:event_btEditarActionPerformed

    private void btAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnularActionPerformed
        // TODO add your handling code here:
        // Leer la fila seleccionada
        int fila = tbLista.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una descripcion");
            return;
        }

        // Crear el objeto cliente y asiganr los datos necesarios
        Categoria client = new Categoria();
        client.setIdCategoria((Integer) tbLista.getValueAt(fila, 0));
        if ((Integer) tbLista.getValueAt(fila, 2) == 0) {
            client.setEstado(1);
        } else {
            client.setEstado(0);
        }

        try {
            // Crear el objeto del controlador
            Ctrl_Categoria control = new Ctrl_Categoria();
            var resultado = control.anular(client);

            if (resultado) {
                cargarTabla();
                JOptionPane.showMessageDialog(this, "Registro anulado");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btAnularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCategoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnular;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
